name: bake image

on:
  workflow_dispatch:

jobs:
  bake_docker:
    runs-on: [ ubuntu-latest ]
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/publish-unit-test-result-action:latest